version: "3.8"
networks:
  api:
    driver: bridge


services:
  postgresql:
    image: postgres:14.3-alpine3.16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./data/scripts:/docker-entrypoint-initdb.d
    networks:
      - api

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - api

  api:
    image: node:lts-alpine3.18
    restart: on-failure
    working_dir: /app
    env_file: .env
    ports:
      - 3000:${SERVER_PORT}
    volumes:
      - ./:/app
    entrypoint: [ "/bin/sh", "-c" , "npm install && npm run dev --host 0.0.0.0" ]
    depends_on:
      - postgresql
    networks:
      - api

volumes:
  postgresql-data: