name: oto_rent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  copy_with_extension: ^5.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  http: ^1.2.0
  json_annotation: ^4.8.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4

flutter:
  uses-material-design: true
